### ISSUE TITLE
by-serial links not deleted upon device removal

### ISSUE THREAD

**Issue by ilovezfs** [cbreak-black/InvariantDisks#3]
It returns here instead of removing the link:

https://github.com/cbreak-black/InvariantDisks/blob/master/InvariantDisks/IDSerialLinker.cpp#L123-L124

@cbreak-black's analysis: "I wasn't able to associate it with any device. Caching. That's what would be needed. Some mapping of devices to serials for the purpose of removability. Anyway, the issue with caching would be that it would be runtime only, but I could re-read the data from existing symlinks on startup. (Not that that'd be too relevant, considering I can just as well delete every symlink and start fresh)."

**Comment by cbreak-black** [comment]
Commit 980b851d should resolve this issue. All link creating device handlers now store which links they created, and remove them again when they get a remove event, even if only the BSD Name is available (but that name must be available).
All links are also removed on normal termination. (But not on crashes)
